theme: ARCHITECT
markdown: kramdown
remote_theme: pages-themes/architect@v0.2.0
gem "github-pages", group: :jekyll_plugins
title: [The title of your site]
description: [A short description of your site's purpose]
